name: 'Deploy to EC2'
description: 'Deploy Docker image to EC2'
inputs:
  ecr-registry:
    required: true
  ecr-repository:
    required: true
  image-tag:
    required: true
  mongo-uri:
    required: true
  groq-api-key:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Pull & Deploy
      shell: bash
      env:
        ECR_REGISTRY: ${{ inputs.ecr-registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        MONGO_URI: ${{ inputs.mongo-uri }}
        GROQ_API_KEY: ${{ inputs.groq-api-key }}
      run: |
        echo "🚀 Deploying $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        
        # Pull image
        docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        # Stop & remove ANY hrchacha containers
        docker stop hrchacha || true && \
        docker rm hrchacha || true && \
        echo "🗑️ Old containers removed"
        
        # Run with explicit container name
        docker run -d \
          --name hrchacha \
          --restart unless-stopped \
          --memory=512m \
          --cpus=0.5 \
          -p 8501:8501 \
          -e MONGO_URI="$MONGO_URI" \
          -e GROQ_API_KEY="$GROQ_API_KEY" \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        # Wait & health check
        sleep 10
        echo "📊 Container status:"
        docker ps -a --filter "name=hrchacha"
        
        # Test endpoint
        if curl -f -m 5 http://localhost:8501/_stcore/health; then
          echo "✅ Streamlit healthy!"
        else
          echo "⏳ Streamlit starting... (normal)"
        fi
